name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: run cmake
        run: cmake $GITHUB_WORKSPACE
      - name: run tests
        run: ./test_suite
