name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: install-cmake
        uses: Symbitic/install-cmake@v0.1.0
      - name: run cmake
        run: cmake build/
      - name: run tests
        run: ./build/tests
